<a href="https://colab.research.google.com/github/savagecm/CS-Notes/blob/master/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
from __future__ import print_function
# importing required modules 
from zipfile import ZipFile 
import requests
import numpy as np
import pandas as pd
import os

# specifying the zip file name 
train_file_name = "orange_small_train.data.zip"
test_file_name = "orange_small_test.data.zip"
trainAppetencyName = "orange_small_train_appetency.labels"
trainChrunName = "orange_small_train_churn.labels"
trainUpselling = "orange_small_train_upselling.labels"


def downloadFile(fileName):
  urlBase = "https://www.kdd.org/cupfiles/KDDCupData/2009/"
  urlName = urlBase+fileName
  print("download file from URL : ", urlName)
  response = requests.get(urlName, stream=True)
  response.status_code
  with open(fileName, "wb") as code:
    code.write(response.content)
  return

def downloadZipFile(fileName):
  urlBase = "https://www.kdd.org/cupfiles/KDDCupData/2009/"
  urlName = urlBase+fileName
  print("download file from URL : ", urlName)
  response = requests.get(urlName, stream=True)
  response.status_code
  with open(fileName, "wb") as code:
    code.write(response.content)
  # opening the zip file in READ mode 
  with ZipFile(fileName, 'r') as zip: 
    # extracting all the files 
    print('Extracting all the files now...') 
    zip.extractall() 
    print('Done!') 
  return





downloadZipFile(train_file_name);
downloadZipFile(test_file_name);
downloadFile(trainAppetencyName);
downloadFile(trainChrunName);
downloadFile(trainUpselling);


print(os.listdir(os.getcwd()))

download file from URL :  https://www.kdd.org/cupfiles/KDDCupData/2009/orange_small_train.data.zip
Extracting all the files now...
Done!
download file from URL :  https://www.kdd.org/cupfiles/KDDCupData/2009/orange_small_test.data.zip
Extracting all the files now...
Done!
download file from URL :  https://www.kdd.org/cupfiles/KDDCupData/2009/orange_small_train_appetency.labels
download file from URL :  https://www.kdd.org/cupfiles/KDDCupData/2009/orange_small_train_churn.labels
download file from URL :  https://www.kdd.org/cupfiles/KDDCupData/2009/orange_small_train_upselling.labels
['.config', 'orange_small_test.data.cksum', 'orange_small_train.data.cksum', 'orange_small_train.data.zip', 'orange_small_train_churn.labels', 'orange_small_train.data', 'orange_small_test.data', 'orange_small_train_upselling.labels', 'orange_small_train_appetency.labels', 'orange_small_test.data.zip', 'sample_data']

read csv data

In [0]:
train = pd.read_csv ('orange_small_train.data',sep ='\t')
train.head(20)

In [0]:
test = pd.read_csv ('orange_small_test.data',sep ='\t')
test.head(20)

In [0]:
appetency = pd.read_table('orange_small_train_appetency.labels', header = None).loc[:, 0].astype('category')
appetency.head(20)

In [0]:
churn = pd.read_table('orange_small_train_churn.labels', header = None).loc[:, 0].astype('category')
churn.head(20)

In [36]:
upselling= pd.read_table('orange_small_train_upselling.labels', header = None).loc[:, 0].astype('category')
churn.head()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.

0   -1
1    1
2   -1
3   -1
4   -1
Name: 0, dtype: category
Categories (2, int64): [-1, 1]

In [37]:
train.describe()

             Var1         Var2           Var3  ...         Var190  Var209  Var230
count  702.000000  1241.000000    1240.000000  ...     333.000000     0.0     0.0
mean    11.487179     0.004029     425.298387  ...   22007.045192     NaN     NaN
std     40.709951     0.141933    4270.193518  ...   29085.146490     NaN     NaN
min      0.000000     0.000000       0.000000  ...       0.000000     NaN     NaN
25%      0.000000     0.000000       0.000000  ...    2732.670000     NaN     NaN
50%      0.000000     0.000000       0.000000  ...   12668.940000     NaN     NaN
75%     16.000000     0.000000       0.000000  ...   29396.340000     NaN     NaN
max    680.000000     5.000000  130668.000000  ...  230427.000000     NaN     NaN

[8 rows x 192 columns]